### PR TITLE
Added ability to run without ext. services

### PR DESCRIPTION
**Pull request by uglrl**
Make sure, you have done de following before merging this pull request:
- [x] Your code is **documented** using doc comments.
- [x] You added appropriate **logging** in your code.
- [x] You added **unit tests** to all your implemented functions.
- [x] You ran `cargo format` and `cargo clippy` to format your code and check for improvements.

### CODE REVIEW

**Review by worldofjoni — COMMENTED** [review]
Nice that you worked on that @uglrl!
I think it would be cleaner to add a command line option to the existing executable for running in isolated _demo mode_ as this is mainly a code duplication. Similar to how the help page or `should_migrate` is done.
That could be tricky, however, because of the generic type parameters.

**Comment by uglrl** [comment]
I thought about doing that, but decided against it, since it would make the normal code flow more difficult to read and understand.

**Comment by worldofjoni** [comment]
Alright. I think, however, that naming the fine just `bin.rs` inside the startup folder is very misleading---something like `standalone_demo_bin.rs` would be clearer.
Also, the usage of this standalone version should be mentioned in the backend readme.

**Review by worldofjoni — CHANGES_REQUESTED** [review]
Alright. I think, however, that naming the fine just `bin.rs` inside the startup folder is very misleading---something like `standalone_demo_bin.rs` would be clearer.
Also, the usage of this standalone version should be mentioned in the backend readme.

**Review by worldofjoni — APPROVED** [review]

**Pull request merged**
