### PR TITLE
Nutrition/app

### PR DESCRIPTION
**Pull request by muety**
Blocked by #146.

### CODE REVIEW

**Comment by muety** [comment]
@uglrl @worldofjoni @ElenaHaeussler @AlexKutschera Has anyone of you had some time to look into this yet? :-)

**Review by worldofjoni — COMMENTED** [review]
The (tiny) frontend GraphQL part looks good to me ;)
For the rest, I am not an expert.

**Comment by muety** [comment]
Any news on this?

**Comment by worldofjoni** [comment]
@AlexKutschera ?

**Review by AlexKutschera — APPROVED** [review]

**Pull request merged**
